default: &default
  adapter: postgresql
  database: <%= Rails.application.credentials.fetch(:database_url) %>
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
